FROM oven/bun:1 

WORKDIR /app

# Copy package.json from the current directory
COPY package.json ./

RUN bun install

# Copy all files from the current directory
COPY . .

EXPOSE 3000

CMD ["bun", "run", "dev"] 